"use client";

import { Trophy } from "lucide-react";
import Link from "next/link";
import { useQueryClient } from "@tanstack/react-query";
import { useLeaderboard } from "@/hooks/use-leaderboard";
import { Skeleton } from "@/components/ui/skeleton";
import { cn } from "@/lib/utils";

function BigStat({
  label,
  value,
  color,
  sub,
}: {
  label: string;
  value: string | number;
  color?: string;
  sub?: string;
}) {
  return (
    <div className="rounded-lg border border-zinc-800 bg-zinc-900/50 p-4 text-center">
      <p className={cn("text-3xl font-bold", color || "text-zinc-200")}>
        {value}
      </p>
      <p className="text-xs text-zinc-500">{label}</p>
      {sub && <p className="mt-1 text-[10px] text-zinc-600">{sub}</p>}
    </div>
  );
}

function SetupRow({
  setup,
  data,
}: {
  setup: string;
  data: { total: number; wins: number; win_rate: number };
}) {
  return (
    <div className="flex items-center justify-between rounded-lg border border-zinc-800 bg-zinc-900/50 px-4 py-3">
      <div>
        <p className="text-sm font-medium text-cyan-400">{setup}</p>
        <p className="text-xs text-zinc-500">{data.total} signals tracked</p>
      </div>
      <div className="flex items-center gap-3">
        <div className="h-2 w-24 rounded-full bg-zinc-800">
          <div
            className={cn(
              "h-full rounded-full",
              data.win_rate >= 60
                ? "bg-emerald-400"
                : data.win_rate >= 45
                  ? "bg-amber-400"
                  : "bg-red-400"
            )}
            style={{ width: `${Math.min(data.win_rate, 100)}%` }}
          />
        </div>
        <span
          className={cn(
            "min-w-[3rem] text-right font-mono text-sm font-bold",
            data.win_rate >= 60
              ? "text-emerald-400"
              : data.win_rate >= 45
                ? "text-amber-400"
                : "text-red-400"
          )}
        >
          {data.win_rate}%
        </span>
      </div>
    </div>
  );
}

export default function LeaderboardPage() {
  const queryClient = useQueryClient();
  const { data, isLoading, isError } = useLeaderboard();
  const stats = data?.stats;
  const bySetup = data?.by_setup || {};
  const recent = data?.recent || [];

  // Sort setups by win rate
  const sortedSetups = Object.entries(bySetup).sort(
    (a, b) => b[1].win_rate - a[1].win_rate
  );

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-3">
        <Trophy className="h-5 w-5 text-amber-400" />
        <h1 className="text-lg font-bold">Signal Leaderboard</h1>
        <span className="text-xs text-zinc-500">
          Live signal accuracy tracking
        </span>
      </div>

      <div className="rounded-lg border border-zinc-800 bg-zinc-900/50 p-3 text-xs text-zinc-400">
        Every signal generated by the Momentum Signal Engine is recorded and
        tracked. After 10 trading days, outcomes are checked against
        target/stop levels. This page shows real, unedited results.
      </div>

      {isError ? (
        <div className="rounded-lg border border-red-800/30 bg-red-900/10 p-8 text-center">
          <p className="text-sm text-zinc-300">Failed to load data.</p>
          <button onClick={() => queryClient.invalidateQueries({ queryKey: ["leaderboard"] })} className="mt-3 text-xs text-cyan-400 hover:underline">Try again</button>
        </div>
      ) : isLoading ? (
        <div className="space-y-3">
          <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
            {Array.from({ length: 4 }).map((_, i) => (
              <Skeleton key={i} className="h-24 bg-zinc-800" />
            ))}
          </div>
        </div>
      ) : stats ? (
        <>
          {/* Top Stats */}
          <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
            <BigStat
              label="Win Rate"
              value={`${stats.win_rate}%`}
              color={
                stats.win_rate >= 50 ? "text-emerald-400" : "text-red-400"
              }
            />
            <BigStat
              label="Signals Resolved"
              value={data?.resolved || 0}
              sub={`${data?.pending || 0} pending`}
            />
            <BigStat
              label="Wins"
              value={stats.total_wins}
              color="text-emerald-400"
            />
            <BigStat
              label="Losses"
              value={stats.total_losses}
              color="text-red-400"
            />
          </div>

          {/* By Setup Type */}
          {sortedSetups.length > 0 && (
            <div className="space-y-3">
              <h2 className="text-sm font-medium text-zinc-300">
                Accuracy by Setup Type
              </h2>
              <div className="space-y-2">
                {sortedSetups.map(([setup, d]) => (
                  <SetupRow key={setup} setup={setup} data={d} />
                ))}
              </div>
            </div>
          )}

          {/* Recent Signals */}
          {recent.length > 0 && (
            <div className="space-y-3">
              <h2 className="text-sm font-medium text-zinc-300">
                Recent Signals
              </h2>
              <div className="overflow-x-auto rounded-lg border border-zinc-800">
                <table className="w-full text-xs">
                  <thead>
                    <tr className="border-b border-zinc-800 bg-zinc-900/50 text-left text-zinc-400">
                      <th className="px-3 py-2 font-medium">Date</th>
                      <th className="px-3 py-2 font-medium">Symbol</th>
                      <th className="px-3 py-2 font-medium">Action</th>
                      <th className="px-3 py-2 font-medium">Setup</th>
                      <th className="px-3 py-2 font-medium text-right">
                        Entry
                      </th>
                      <th className="px-3 py-2 font-medium text-right">
                        Target
                      </th>
                      <th className="px-3 py-2 font-medium text-right">
                        Stop
                      </th>
                      <th className="px-3 py-2 font-medium">Outcome</th>
                    </tr>
                  </thead>
                  <tbody>
                    {recent.map((s, i) => (
                      <tr
                        key={i}
                        className="border-b border-zinc-800/30 hover:bg-zinc-800/20"
                      >
                        <td className="px-3 py-1.5 text-zinc-500">
                          {s.recorded_at
                            ? new Date(s.recorded_at).toLocaleDateString(
                                "en-US",
                                { month: "short", day: "numeric" }
                              )
                            : "-"}
                        </td>
                        <td className="px-3 py-1.5">
                          <Link
                            href={`/chart/${s.symbol}`}
                            className="text-cyan-400 hover:underline"
                          >
                            {s.symbol}
                          </Link>
                        </td>
                        <td className="px-3 py-1.5">
                          <span
                            className={
                              s.action === "BUY"
                                ? "text-emerald-400"
                                : "text-red-400"
                            }
                          >
                            {s.action}
                          </span>
                        </td>
                        <td className="px-3 py-1.5 text-zinc-400">
                          {s.setup_type}
                        </td>
                        <td className="px-3 py-1.5 text-right font-mono text-zinc-300">
                          ${s.entry.toFixed(2)}
                        </td>
                        <td className="px-3 py-1.5 text-right font-mono text-emerald-400/60">
                          ${s.target.toFixed(2)}
                        </td>
                        <td className="px-3 py-1.5 text-right font-mono text-red-400/60">
                          ${s.stop_loss.toFixed(2)}
                        </td>
                        <td className="px-3 py-1.5">
                          {s.outcome ? (
                            <span
                              className={cn(
                                "rounded-full px-2 py-0.5 text-[10px] font-medium",
                                s.outcome === "win"
                                  ? "bg-emerald-400/10 text-emerald-400"
                                  : "bg-red-400/10 text-red-400"
                              )}
                            >
                              {s.outcome.toUpperCase()}
                            </span>
                          ) : (
                            <span className="rounded-full bg-zinc-400/10 px-2 py-0.5 text-[10px] text-zinc-500">
                              PENDING
                            </span>
                          )}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </>
      ) : (
        <div className="rounded-lg border border-zinc-800 p-12 text-center text-zinc-500">
          No signals tracked yet. The leaderboard populates automatically as
          the scanner generates signals. Check back after the market opens.
        </div>
      )}
    </div>
  );
}
