/**
 * CSV and report export utilities.
 * Feature #39: CSV export for all tables
 * Feature #40: Print-friendly report generator
 */

export function exportCsv(data: Record<string, unknown>[], filename: string) {
  if (!data.length) return;

  const headers = Object.keys(data[0]);
  const csvRows = [
    headers.join(","),
    ...data.map((row) =>
      headers.map((h) => {
        const val = row[h];
        const str = val === null || val === undefined ? "" : String(val);
        return str.includes(",") || str.includes('"') ? `"${str.replace(/"/g, '""')}"` : str;
      }).join(",")
    ),
  ];

  const blob = new Blob([csvRows.join("\n")], { type: "text/csv" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${filename}_${new Date().toISOString().slice(0, 10)}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

export function printReport(title: string, content: string) {
  const win = window.open("", "_blank");
  if (!win) return;

  win.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title} - MSE Report</title>
      <style>
        body { font-family: system-ui, sans-serif; padding: 2rem; color: #333; }
        h1 { font-size: 1.5rem; border-bottom: 2px solid #0891b2; padding-bottom: 0.5rem; }
        table { width: 100%; border-collapse: collapse; margin: 1rem 0; }
        th, td { border: 1px solid #ddd; padding: 0.5rem; text-align: left; font-size: 0.875rem; }
        th { background: #f5f5f5; font-weight: 600; }
        .positive { color: #16a34a; } .negative { color: #dc2626; }
        .meta { color: #888; font-size: 0.75rem; }
        @media print { body { padding: 0; } }
      </style>
    </head>
    <body>
      <h1>${title}</h1>
      <p class="meta">Generated by Momentum Signal Engine on ${new Date().toLocaleString()}</p>
      ${content}
    </body>
    </html>
  `);
  win.document.close();
  win.print();
}

export function tableToHtml(data: Record<string, unknown>[], columns?: string[]): string {
  if (!data.length) return "<p>No data</p>";
  const headers = columns || Object.keys(data[0]);
  const rows = data.map((row) =>
    headers.map((h) => {
      const val = row[h];
      const num = Number(val);
      const cls = !isNaN(num) && num !== 0 ? (num > 0 ? "positive" : "negative") : "";
      return `<td class="${cls}">${val ?? "-"}</td>`;
    }).join("")
  );

  return `<table><thead><tr>${headers.map((h) => `<th>${h}</th>`).join("")}</tr></thead><tbody>${rows.map((r) => `<tr>${r}</tr>`).join("")}</tbody></table>`;
}
